<?php
// ----------------------------------------------------------------
// Error checking and sticky forms
// This version shows how to make a group of radio buttons sticky.
// ----------------------------------------------------------------


if (isset($_REQUEST['button'])) // submit was clicked
{
   $error = validate_form();
   if ($error)
   {
      display_form_page($error);
   }
   else
   {
      display_output_page();
   }
}
else // display form for first time
{
   display_form_page('');
}
// ---------------------------------------------------------------------
?>

<?php
function display_form_page($error)
{
   $self = $_SERVER['PHP_SELF'];
   $first_name = isset($_REQUEST['firstname']) ? $_REQUEST['firstname'] : '';
   $last_name = isset($_REQUEST['lastname']) ? $_REQUEST['lastname'] : '';
   $wine = isset($_REQUEST['wine']) ? $_REQUEST['wine'] : '';
   ?>
<html>
<head>
<link rel="stylesheet" type="text/css" href="input.css"/>
<title>Sticky radio buttons</title>
<style type="text/css">
.error { color: #ff0000 }
</style>
</head>
<body
<h1>Sticky radio buttons</h1>

In this version the form is generated by PHP script using error checking
and sticky forms.<br>
The form is submitted using GET so you can see the query string.

<?php
if ($error)
{
   echo "<p>$error</p>\n";
}
?>

<form action="<?php echo $self ?>" method="GET">
<p>First name: <input class="input" type="text" name="firstname"
   value="<?php echo $first_name?>"></p>
<p>Last name: <input class="input" type="text" name="lastname"
   value="<?php echo $last_name?>"></p>
<p>Choose your favorite wine:</p>
<p>
Shiraz <input type="radio" name="wine" value="shiraz" <?php check($wine,"shiraz")?>>
Merlot <input type="radio" name="wine" value="merlot" <?php check($wine,"merlot")?>>
Chianti <input type="radio" name="wine" value="chianti" <?php check($wine,"chianti")?>>
</p>
<p><input type="submit" name="button" value="Submit Name"></p>
</form>

</body>
</html>
<?php
}
?>


<?php
// If $group has the value $val then check this radio button
function check($group, $val)
{
   if ($group === $val)
   {
      echo 'checked = "checked"';
   }
}
?>


<?php
function validate_form()
{
   $first_name = trim($_REQUEST['firstname']);
   $last_name = trim($_REQUEST['lastname']);
   $wine = isset($_REQUEST['wine']) ? $_REQUEST['wine'] : '';

   $error = '';
   $reg_exp = "/^[a-zA-Z'-]+$/";
   if (! preg_match($reg_exp, $first_name))
   {
      $error .=
      "<span class=\"error\">First name is invalid (letters, hyphens, ', only)</span><br>";
   }
   if (! preg_match($reg_exp, $last_name))
   {
      $error .=
      "<span class=\"error\">Last name is invalid (letters, hyphens, ', only)</span><br>";
   }
   if (strlen($wine) == 0)
   {
      $error .=
      "<span class=\"error\">Select a wine</span><br>";
   }
   return $error;
}
?>

<?php
// -----------------------------------------------------------------------------
function display_output_page()
{
   $first_name = trim($_REQUEST['firstname']);
   $last_name = trim($_REQUEST['lastname']);
   $wine = isset($_REQUEST['wine']) ? $_REQUEST['wine'] : '';
?>
   <html>
   <head><title>Form Results</title></head>
   <body>
   <h1>Form Results</h1>
   <?php
      echo "Hello $first_name $last_name<br/>\n";
      echo "Favorite wine is $wine<br/>\n";
   ?>
   </body>
   </html>
<?php
}
?>
