<?php
// ----------------------------------------------------------------
// Error checking and sticky forms
// This version shows how to make a group of checkboxes sticky.
// ----------------------------------------------------------------

if (isset($_REQUEST['button'])) // submit was clicked
{
   $error = validate_form();
   if ($error)
   {
      display_form_page($error);
   }
   else
   {
      display_output_page();
   }
}
else // display form for first time
{
   display_form_page('');
}
?>


<?php
function display_form_page($error)
{
   $self = $_SERVER['PHP_SELF'];
   $first_name = isset($_REQUEST['firstname']) ? $_REQUEST['firstname'] : '';
   $last_name = isset($_REQUEST['lastname']) ? $_REQUEST['lastname'] : '';
   $wines = isset($_REQUEST['wines']) ? $_REQUEST['wines'] : '';
   ?>
<html>
<head>
<link rel="stylesheet" type="text/css" href="input.css"/>
<title>Sticky checkboxes</title>
<style type="text/css">
.error { color: #ff0000 }
</style>
</head>
<body
<h1>Sticky Checkboxes</h1>

In this version the form is generated by PHP script using error checking
and sticky forms.<br>
The form is submitted using GET so you can see the query string.


<?php
if ($error)
{
   echo "<p>$error</p>\n";
}
?>


<form action="<?php echo $self ?>" method="GET">
<p>First name: <input class="input" type="text" name="firstname"
   value="<?php echo $first_name?>"></p>
<p>Last name: <input class="input" type="text" name="lastname"
   value="<?php echo $last_name?>"></p>
<p>Choose your favorite wines:</p>
Shiraz <input type="checkbox" name="wines[]" value="shiraz" <?php check($wines,"shiraz")?>>
Merlot <input type="checkbox" name="wines[]" value="merlot" <?php check($wines,"merlot")?>>
Chianti <input type="checkbox" name="wines[]" value="chianti" <?php check($wines,"chianti")?>>
<p><input type="submit" name="button" value="Submit Name"></p>
</form>
</body>
</html>
<?php
}
?>


<?php
// If $val is in the $wines array then check this checkbox
function check($wines, $val)
{
   if (is_array($wines) and in_array($val, $wines))
   {
      echo 'checked = "checked"';
   }
}
?>


<?php
function validate_form()
{
   $first_name = trim($_REQUEST['firstname']);
   $last_name = trim($_REQUEST['lastname']);
   $wines = isset($_REQUEST['wines']) ? $_REQUEST['wines'] : '';

   $error = '';
   $reg_exp = "/^[a-zA-Z'-]+$/";
   if (! preg_match($reg_exp, $first_name))
   {
      $error .=
      "<span class=\"error\">First name is invalid (letters, hyphens, ', only)</span><br>";
   }
   if (! preg_match($reg_exp, $last_name))
   {
      $error .=
      "<span class=\"error\">Last name is invalid (letters, hyphens, ', only)</span><br>";
   }
   if (! is_array($wines))
   {
      $error .= "<span class=\"error\">You must select at least one wine</span></br>";
   }
   return $error;
}
?>

<?php
// -----------------------------------------------------------------------------
function display_output_page()
{
   $first_name = trim($_REQUEST['firstname']);
   $last_name = trim($_REQUEST['lastname']);
   $wines = isset($_REQUEST['wines']) ? $_REQUEST['wines'] : '';
?>
   <html>
   <head><title>Form Results</title></head>
   <body>
   <h1>Form Results</h1>
   <?php
      echo "Hello $first_name $last_name<br/>\n";

      if (is_array($wines))
      {
         echo "Favorite wines are ";
         foreach ($wines as $wine)
         {
            echo $wine, " ";
         }
      }
   ?>
   </body>
   </html>
<?php
}
?>

