<!DOCTYPE HTML PUBLIC
   "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html401/loose.dtd">
<?php
// Shows how to use two buttons.
// This script is called when either button is clicked so one button
// name will be undefined and the other will be defined.

echo "<u>Script displays Form with 2 Buttons & Checks which button is pressed </u> <p>";

if (isset($_REQUEST['button1']) || isset($_REQUEST['button2']))
{
   display_output_page();
}
else
{
   display_form_page();
}
?>


<?php
function display_form_page()
{
   $self = $_SERVER['PHP_SELF'];
?>
   <html>
   <head>
   <title>Forms, version 3</title>
   <link rel="stylesheet" type="text/css" href="input.css"/>
   </head>

   <body>
   <h1>Forms, version 3</h1>

   In this version the form is generated by the PHP script.<br/>
   There are two buttons and we need to determine which one was clicked.
   <p>
   <form action="<?php echo $self ?>" method="POST">
   <p>First  name: <input class="input" type="text" name="firstname"></p>
   <p>Last name: <input class="input" type="text" name="lastname"></p>
   </p>
   <p>
   <input type="submit" name="button1" value="Submit Name 1">
   <input type="submit" name="button2" value="Submit Name 2">
   </form>
   </p>
   </body>
   </html>
<?php
}
?>

<?php
function display_output_page()
{
   $first_name = trim($_REQUEST['firstname']);
   $last_name = trim($_REQUEST['lastname']);
   $button1 = isset($_REQUEST['button1']) ? $_REQUEST['button1'] : '';
   $button2 = isset($_REQUEST['button2']) ? $_REQUEST['button2'] : '';
?>
   <html>
   <head><title>Form Results</title></head>
   <body>
   <h1>Form Results</h1>

   <?php
   echo "Hello $first_name $last_name<br/>\n";

   if ($button1 != '')
   {
      echo "You clicked the button named button1 with label '$button1'.<br/>\n";
   }
   if ($button2 != '')
   {
      echo "You clicked the button named button2 with label '$button2'.<br/>\n";
   }
   ?>

   </body>
   </html>
<?php
}
?>
